name: "Reusable action"
description: "Reuse..."
inputs:
  dotnet-version:
    description: 'The version to use'
    default: '0.0.1'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Get PR Value
      run: echo 'PR = "${{github.event.pull_request.number}}" ,State = "${{github.event.review.state}}" ,User = "${{github.actor}}" ,Event Name = "${{github.event_name}}" '