name: "Shortcut Status Comment"
description: "A shortcut integration that adds comment to a ticket"

inputs:
  shortcut_token:
    description: "secret shortcut token"
    default: 'shortcut_token'
    required: true
  github_token:
    description: "secret github token"
    default: 'git_token'
    required: true
  pull_request_number:
    description: "pull request number"
    required: true
  pull_request_state:
    description: "used to trigger the pull review commenter in the javascript"
    required: false
  pull_request_actor:
    description: "used to identify who made the trigger"
    required: false
  work_dir:
    description: "reference to the javascript file directory"
    required: true
  filename:
    description: "name of the javascript file that will be executed"
    required: true

runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so job can access it
    - uses: actions/checkout@v3

    # Print the input data in the console
    - name: Get Input Value
      shell: bash
      run: echo 'PR = "${{inputs.pull_request_number}}" ,State = "${{inputs.pull_request_state}}" ,User = "${{inputs.pull_request_actor}}" ,Event Name = "${{github.event_name}}" '
    - name: Install dependencies
      shell: bash
      working-directory: ${{input.work_dir}}
      run: yarn
      env:
        NODE_AUTH_TOKEN: ""

    # Pulls github PR data and feeds it to JS file, which posts comment
    - name: Shortcut Comments
      shell: bash
      run: node ${{input.work_dir}}/${{input.filename}} "${{inputs.shortcut_token}}" "${{inputs.github_token}}" "${{inputs.pull_request_number}}" "${{inputs.pull_request_state}}" "${{inputs.pull_request_actor}}"