name: "Reusable action"
description: "Reuse..."

inputs:
  github_token:
    description: 'secret github token'
    default: 'git_token'
    required: true
  shortcut_token:
    description: 'secret shortcut token'
    default: 'shortcut_token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Get PR Value
      shell: bash
      run: echo 'PR = "${{github.event.pull_request.number}}" ,State = "${{github.event.review.state}}" ,User = "${{github.actor}}" ,Event Name = "${{github.event_name}}" '

  - name: Install dependencies
        working-directory: .github/shortcut
        run: yarn
        env:
          NODE_AUTH_TOKEN: ""

    # Pulls github PR data and feeds it to JS file, which says hello
    - name: Shortcut Comments
      run: node .github/shortcut/hello.js "${{inputs.shortcut_token}}" "${{inputs.github_token}}" "${{github.event.pull_request.number}}" "PR_REVIEW" "${{github.actor}}"